### ISSUE TITLE
Best Submissions ID

### ISSUE THREAD

**Issue by FlatPaper** [Ninjaclasher/dmoj-submission-downloader#2]
Isn't it possible to get the submission ids faster for best submissions if you go through `https://dmoj.ca/problem/{problem_code}/rank/{page_num}` instead of doing the following, or am I missing something here?

```py
        if self.best_only:
            self.echo('Parsing submissions and only storing best...')
            user_mp = {}
            for sub in self.ids:
                try:
                    user_mp[sub[2]] = min(user_mp[sub[2]], (sub[1], sub[0]))
                except KeyError:
                    user_mp[sub[2]] = (sub[1], sub[0])
            self.ids = list(map(itemgetter(1), user_mp.values()))
        else:
            self.ids = list(map(itemgetter(0), self.ids))
```

**Comment by Ninjaclasher** [comment]
"Best" submissions doesn't mean the submission that scored the most points. It means the first submission that matches the order defined [here](https://github.com/Ninjaclasher/dmoj-submission-downloader/blob/master/downloader.py#L17). For example, if a user's had two submissions that both received 0 points, one that TLEs and one that WAs, it would grab the WA submission. On the other hand, only looking at best submissions might not grab any submissions by that user at all as both submissions scored 0 points.

**Comment by FlatPaper** [comment]
Oh ok, I see. Thanks!
